### ISSUE TITLE
Why onCreate is overriden in basic example?

### ISSUE THREAD

**Issue by farmazon3000** [soundcloud/lightcycle#43]
In basic example we have SampleActivity
https://github.com/soundcloud/lightcycle/blob/master/examples/basic/src/main/java/com/soundcloud/lightcycle/sample/basic/SampleActivity.java

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }
```

What is the purpose of this overriding, if you didn't add this method to SampleActivity at all effect would have been the same, wouldn't it?

**Comment by glung** [comment]
None : ) 

Removing it atm. Thank you.
