### ISSUE TITLE
Custom Views support

### ISSUE THREAD

**Issue by cesards** [soundcloud/lightcycle#55]
Hi guys!

First of all, awesome job! I really think having the change to split the bunch of logic in a Presenter, is the way to go. 

I was wondering how do you manage to support custom views. I want to add a "presenter" to a custom view which does an specific logic, so I don't to depend on fragments or activities. If you are not handling view life cycles yet, I could try to have a deeper look and do a PR, but I wanted to ask first.

Thanks in advance again.

**Comment by glung** [comment]
Hello Cesards,

I guess you want to follow the MVP pattern and have the following flow  : Presenter -> View. 

In the context of LightCycle : 
- Presenters are only attached to Activity, Fragment or any another LightCycle dispatcher. 
- Only the Activity and Fragment know about the android resources. 

From this, you may consider your (Activity + custom view) as the V of MVP.

For instance, one approach would be to make your `MyFeatureActivity` implement a `MyFeatureView` interface. In this context, your activity is free to proxy any custom view specifics - which then is an implementation detail your presenter does not need to know about. 

I hope it answers your Q.
