### ISSUE TITLE
LightCycle NullPointerException using my own Dispatcher

### ISSUE THREAD

**Issue by cesards** [soundcloud/lightcycle#61]
I'm having some troubles using a custom dispatcher. When I dispatch the `onCreate` I get a `NullPointerException`:

![screen shot 2016-10-31 at 09 42 55](https://cloud.githubusercontent.com/assets/1536079/19850117/a50eb2f0-9f4e-11e6-8890-87b2af34eec1.png)

Here is my structure:

#### HomeActivity
```java
public class HomeActivity extends AppCompatActivity implements LightCycleDispatcher<ActivityLightCycle<HomeActivity>> {

    private final ActivityLightCycleDispatcher<HomeActivity> lightCycleDispatcher;

    private ActivityHomeBinding binding;
    @LightCycle FeedViewAction feedViewAction;

    public HomeActivity() {
        lightCycleDispatcher = new ActivityLightCycleDispatcher<>();
    }

    @Override
    public void bind(ActivityLightCycle<HomeActivity> lightCycle) {
        lightCycleDispatcher.bind(lightCycle);
    }

    public static Intent getCallingIntent(@NonNull final Context context) {
        return new Intent(context, HomeActivity.class);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = DataBindingUtil.setContentView(this, R.layout.activity_home);
        setupToolbar();
        LightCycles.bind(this);
        lightCycleDispatcher.onCreate(this, savedInstanceState);
    }
    
    ...
}
```

#### FeedViewAction
```java
public class FeedViewAction extends BaseViewAction<HomeActivity> {

    @Override
    public void onCreate(HomeActivity activity, Bundle bundle) {
        super.onCreate(activity, bundle);

        activity.setupFeedViews();
    }
}
```

#### BaseViewAction
```java
public abstract class BaseViewAction<A extends Activity> extends DefaultActivityLightCycle<A> {

    protected final CompositeSubscription compositeSubscription = new CompositeSubscription();

    @Override
    public void onDestroy(A activity) {
        compositeSubscription.clear();
        super.onDestroy(activity);
    }
}
```

I've reviewed what could be wrong, and either is a silly mistake I made, or the documentation is not completed at all. Actually I was going to fork the repo and update it, because I think there should be a sample or at least a more completed `HowTo` use a custom dispatcher.

Thanks in advance!

**Comment by glung** [comment]
Is `feedViewAction` initialized before ` LightCycles.bind(this);` ?

**Comment by cesards** [comment]
Mmm I think I don't get it. I never had to initialise the binded components before, using [LightAppCompatActivity](https://github.com/soundcloud/lightcycle/blob/master/lightcycle-lib/src/main/java/com/soundcloud/lightcycle/LightCycleAppCompatActivity.java)

This class also depends on the dispatcher and there is no initialisation anywhere. Am I missing something? I was going to open a PR to update the documentation and include the initialisation of the dispatcher in the sample(I had problems as other people too, but then I had to figure it how the library works behind the scenes.), but that has nothing to do with the current problem I'm having.

```
public ActivityX() {
    lightCycleDispatcher = new ActivityLightCycleDispatcher<>();
}
```

**Comment by cesards** [comment]
Yep, my fault. It was a mess because I was migrating to Dagger at the same time, and somehow I thought the dispatcher was able to instantiate the controllers. 🍻  Thanks!

**Comment by cesards** [comment]
```
@Inject @LightCycle AuthenticationViewAction authenticationViewAction
```
Source of all my problems :-)
