### ISSUE TITLE
Add formatter and check style 

### ISSUE THREAD

**Issue by glung** [soundcloud/lightcycle#65]
Fail the build when the code style is not applied.

**Comment by NikoYuwono** [comment]
Does Soundcloud has standard checkstyle?
If not maybe I can help to create one for lightcycle.

Things that need to be checked in my opinion : 
- Trailing spaces
- New line (After annotation, after opening bracket, etc)
- Spacing ('for', 'for-each', 'if', etc)
- Imports (Avoid star imports, redundant import, etc)
- Naming Conventions (Camel case, upper case first letter for class, lower case first letter for function, etc)
- Line length

After we decide the rule, we can start creating the checker.

**Comment by glung** [comment]
Let's got with these rule and we can tweak it when it is in place !

**Comment by NikoYuwono** [comment]
OK! Will add it this week!
