### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by NikoYuwono** [soundcloud/lightcycle#71]
Do you guys feel the need for integration test? 
Currently there are individual test per module (lightcycle-lib, lightcycle-processor, lightcycle-api) but there are no integration test. 

This time I asked first because I want to make sure there are no special reason for not implementing integration test.

Thanks!

**Comment by glung** [comment]
It sounds like a good idea. 

What and how would you like to do test ?

**Comment by NikoYuwono** [comment]
So what I imagine is, we can use the basic sample, and modify it a little bit, and verify if the processor working well with the lib.

## What to test : 
Every Activity/Fragment callback

## How to test : 
### Instrumentation test 
For example show a toast on every callback and check if every toast is shown or not.
### Unit test 
Build the Activity/Fragment using Roboelectric, call the Activity/Fragment lifecycle and make sure every callback is called.

Maybe we can start with Activity first and then Fragment later.
Please let me know if you have any feedback or other idea!

**Comment by glung** [comment]
I am concerned with testing on the top of the UI (toasts in this case). 

What do you think about testing on an activity/fragment and access to its fields to check in memory states ? 
Like `assertThat(activity.lightcycle.isOnStartedCalled()).isTrue()`. 

A little similar to https://github.com/JakeWharton/butterknife/tree/master/butterknife-integration-test

**Comment by NikoYuwono** [comment]
Hmmm, Actually I'm not attached to toast, we can change it to other view if you want. Can you give me the reason why are you concerned with testing on the top of the UI?

And yes,  I agree with that like I wrote above, I'm planning to use Roboelectric to do that test. What do you think?

If this looks good to you, I'll implement the callback test first and leave the instrumentation test for later (or might not need to implement it at all)

**Comment by glung** [comment]
Hey, I like your idea to implement integration tests with robolectric.

In this case views are not needed, because we can just assert on in memory
(non-ui) states (sharing an API with the activity/fragment).

Using views as a communication layer between the activity and the test is
to me not necessary and more complex.

Does it make sense?

Am 17.11.2016 1:35 vorm. schrieb "Niko Yuwono" <notifications@github.com>:

**Comment by NikoYuwono** [comment]
OK! Let's use roboelectric for the callback check in memory assertion!
Thanks for the feedback! 
Will try to get some time this weekends to implement that.
Will send a pull request after that 😃

**Comment by glung** [comment]
🔥

Am 17.11.2016 9:54 vorm. schrieb "Niko Yuwono" <notifications@github.com>:
