### ISSUE TITLE
Add support for onBackPressed

### ISSUE THREAD

**Issue by INRIX-Iurii-Okhmat** [soundcloud/lightcycle#77]
Add an option to handle onBackPressed in activity controller. Potentially, something like `boolean handleBackPress()`.

**Comment by NikoYuwono** [comment]
@INRIX-Iurii-Okhmat Currently this is being discussed in API v2.0 planning. pleaser refer to https://github.com/soundcloud/lightcycle/issues/48

**Comment by glung** [comment]
Like @NikoYuwono said ! 

I am closing this one, but please chime in the #48
