### ISSUE TITLE
Add support for onCreateOptionsMenu, onPrepareOptionsMenu

### ISSUE THREAD

**Issue by INRIX-Iurii-Okhmat** [soundcloud/lightcycle#78]
There's a way to handle menu item clicks, but no way to inflate or modify menu items in the activity controller.

**Comment by NikoYuwono** [comment]
@INRIX-Iurii-Okhmat Currently this is being discussed in API v2.0 planning. pleaser refer to https://github.com/soundcloud/lightcycle/issues/48
