### ISSUE TITLE
Provide option to disable logging

### ISSUE THREAD

**Issue by Mauin** [soundcloud/lightcycle#94]
`LightCycles.java` currently logs its search for the LightCycle binder class.
While this might be valuable to debug some issues I feel like we should provide an option to turn this logging off completely to not add extra noise to logs of applications using LightCycle.

**Comment by glung** [comment]
It uses `Log.d(TAG, )`

https://github.com/soundcloud/lightcycle/blob/master/lightcycle-api/src/main/java/com/soundcloud/lightcycle/LightCycles.java#L42

Are you sure the tag has not been enabled for logging in the app?
