### ISSUE TITLE
FragmentLightCycle events not dispatched with Proguard

### ISSUE THREAD

**Issue by cesards** [soundcloud/lightcycle#95]
Hi there!

I'm having troubles with Proguard and `FragmentLightCycle`. I hadn't had that problem before with Activities, but lately I've been working with some fragments, and it looks like the dispatcher doesn't work 

and I'm pretty sure the error is related to proguard, because a non obfuscated apk is working perfectly. I've never had a bug related to an annotation processor. How could I help to fix this? There is no trace. What kind of information should I provide?

**Comment by cesards** [comment]
Here is the code:

My fragment extends a `BaseFragment` which extends from a LightCycle one

**Custom fragment**:
```
public class AccountCreationFragment extends BaseFragment
    implements AccountCreationFragmentAction.View, ConnectionErrorAction.View {

  ...
  @Inject @LightCycle AccountCreationFragmentAction accountCreationAction;
  @Inject @LightCycle ConnectionErrorFragmentAction connectionErrorAction;

   ... 
```

**Base fragment**:

```
public abstract class BaseFragment extends LightCycleFragment<BaseFragment> {

  protected boolean restoredFromBackStack;

  protected boolean seen(Bundle savedInstanceState) {
    return savedInstanceState != null || restoredFromBackStack;
  }

  @Override public void onDestroyView() {
    restoredFromBackStack = true;

    super.onDestroyView();
  }
}
```

**"Presenter"(AccountCreationFragmentAction)**:
```
class AccountCreationFragmentAction extends BaseFragmentAction<BaseFragment> {

@Override protected Disposable[] subscribe() {
    Observable<String> onAccountSelected = view.onAccountSelected().share();

    return new Disposable[] {
      ...
        ,
        onAccountSelected
            .filter(text -> !formFieldValidation.valid(text))
            .subscribe(ignored -> view.showFieldValidationFailed())
        ,
        view.onAccountChangesDone().subscribe(ignored -> view.hideError())
    };
  }
```
And here is my own implementation of `FragmentLightCycle`:
```
public abstract class BaseFragmentAction<F extends Fragment> implements FragmentLightCycle<F> {

  protected final CompositeDisposable compositeDisposable = new CompositeDisposable();

  protected Disposable[] subscribe() {
    return null;
  }

  @Override public void onAttach(F f, Activity activity) { }

  @Override public void onAttach(F f, Context context) { }

  @Override public void onCreate(F f, Bundle bundle) { }

  @Override public void onViewCreated(F f, View view, Bundle bundle) { }

  @Override public void onActivityCreated(F f, Bundle bundle) { }

  @Override public void onStart(F f) {
    compositeDisposable.addAll(subscribe());
  }

  @Override public void onResume(F f) { }

  @Override public boolean onOptionsItemSelected(F f, MenuItem menuItem) {
    return false;
  }

  @Override public void onPause(F f) { }

  @Override public void onStop(F fragment) {
    compositeDisposable.clear();
  }

  @Override public void onSaveInstanceState(F f, Bundle bundle) { }

  @Override public void onDestroyView(F f) { }

  @Override public void onDestroy(F f) { }

  @Override public void onDetach(F f) { }
}
```

I guess it's too much information, but better this than nothing :-/

**Comment by rciovati** [comment]
If you can provide a sample project reproducing this issue I would be glad to take a look at this in the next few days :)

**Comment by cesards** [comment]
Thanks! I will :-) But I don't know if Im going to be able to reproduce the issue. You'll hear from me :-)

**Comment by cesards** [comment]
Hi again @rciovati !

As I promised, here is the sample project with the debug and release apks included. 
The sample consists on an Activity + 2 fragments. All of them are associated to specific actions (lightcycle containers). Because Im using RxJava, the subscriptions to the events are done during `onStart()`.

As you can see, if you click to the **"Message"** button of any of the fragments in the debug apk, it works properly because the onStart is dispatched correctly, but by the time I use proguard on the app, life cycle events are not dispatched on my fragments.

https://github.com/cesards/LightCycleProguard

Let me know if you need any kind of help :-)

**Comment by rciovati** [comment]
Hello @cesards!

Thank you for the sample project, it was really helpful!

I played around with the project and looks like the problem is a partial proguard configuration. 
Since our processor generates the binder using the fragment/activity classname + $$Binder and at runtime tries to retrieve those binders by name we have to make sure both the fragment/activity and the binder classes are not renamed by proguard.

In our proguard config we are keeping the binder classes:

`-keep class **$LightCycleBinder { *; }` 

and in the same way we should keep all the activities/fragments that use Lightcycle. Adding this keep should to the trick:

`-keep class * implements com.soundcloud.lightcycle.LightCycleDispatcher`

From my tests it solves the problem for the sample project, can you try also in your app?

@glung what do you think about this? does it make sense to tweak LC proguard config keeping also the activity/fragment names?

**Comment by glung** [comment]
yes!

**Comment by cesards** [comment]
Hi again @rciovati !

> From my tests it solves the problem for the sample project, can you try also in your app?

It works perfectly! :-) I made some tests and your suggestion makes totally sense. 🍻

**Comment by rciovati** [comment]
Cool, I am glad it works for you as well. Thanks for reporting the issue and taking the time to create a sample project!

**Comment by cesards** [comment]
It was so silly. I doesn't have lots of experience with the darn proguard. I knew it was related to the dispatcher but I didn't know you could a rule specifying `implements` on it (first time I've seen it)
